### ISSUE TITLE
Trouble compiling RMagick

### ISSUE THREAD

**Issue by mockdeep** [tjschuck/rake-compiler-dev-box#26]
Not sure if this is the right place for this issue, but I thought I'd start here. I'm trying to compile RMagick using `rake-compiler-dev-box`. Unfortunately, I get a strange error:

```sh
$ rake
cd tmp/x86_64-linux/RMagick2/2.5.3
make -j2
make: *** No rule to make target '/home/fletch/.rvm/rubies/ruby-2.5.3/include/ruby-2.5.0/ruby.h', needed by 'rmagick.o'.  Stop.
rake aborted!
Command failed with status (2): [make -j2...]
/home/vagrant/.rvm/gems/ruby-2.5.3/gems/rake-compiler-1.0.7/lib/rake/extensiontask.rb:166:in `block (2 levels) in define_compile_tasks'
/home/vagrant/.rvm/gems/ruby-2.5.3/gems/rake-compiler-1.0.7/lib/rake/extensiontask.rb:165:in `block in define_compile_tasks'
/home/vagrant/.rvm/gems/ruby-2.5.3/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => default => spec => compile => compile:x86_64-linux => compile:RMagick2:x86_64-linux => copy:RMagick2:x86_64-linux:2.5.3 => tmp/x86_64-linux/RMagick2/2.5.3/RMagick2.so
```

Something interesting that stood out to me is that it's referencing the ruby in `/home/fletch/.rvm` on my host machine, which was surprising being that it seems to be reaching outside of the Vagrant box, instead of using the ruby version installed on the box. I'm able to compile and run this locally outside of the VM.

**Comment by mockdeep** [comment]
Okay, it seems to be working now after I ran `rvm reinstall 2.5 --disable-binary` per [this old issue](https://github.com/rvm/rvm/issues/1244#issuecomment-9586183). I'll leave this issue open, as I'm not sure if it might warrant an update in `bootstrap.sh`.

**Comment by mockdeep** [comment]
Nevermind, turns out this was caused by build artifacts that were leftover in my directory from a build run outside of the VM.

**Comment by tjschuck** [comment]
Thanks for following up, @mockdeep!
